const questions = [
    { question: "The system bus includes address bus, control bus and (    ) bus.", options: ["data", "character", "signal", "input"], answer: 0 },
    { question: "Any program must be loaded into (    ) to be executed by the CPU.", options: ["Disk", "Hard Disk", "Internal Storage", "External Storage"], answer: 2 },
    { question: "The two main components of a computer are (    ).", options: ["Arithmetic unit and Controller", "Controllers and Registers", "Arithmetic and RAM", "Controller and RAM"], answer: 0 },
    { question: "The decimal number 83 corresponds to the binary number (    ).", options: ["10011", "1010011", "1100101", "1111101"], answer: 1 },
    { question: "The basic structure of the algorithm does not include (    ).", options: ["logical structure", "selective structure", "loop structure", "sequential structure"], answer: 0 },
    { question: "The protocol used for sending and receiving E-mail on the Internet is (    ).", options: ["TCP/IP", "IPX/SPX", "POP3/SMTP", "NetBEUI"], answer: 2 },
    { question: "The .MOV extension is usually a (    ) file.", options: ["audio", "video", "picture", "text"], answer: 1 },
    { question: "Which of the following is not a function of the operating system(    )", options: ["Manage the hardware and software resources of the computer.", "Organize computer workflow properly.", "Complete 'translation' of high-level language programs.", "To provide users with convenient, effective and safe working environment."], answer: 2 },
    { question: "If the time slice of a time-sharing system is constant, then (    ), the longer the response time is.", options: ["The fewer users", "The more users", "The less memory", "The more memory"], answer: 1 },
    { question: "If the memory address space is 16 MB and the word size is 8 bits, then ___ bits are needed to access each word.", options: ["8", "16", "24", "32"], answer: 2 },
    { question: "The three steps in the running of a program on a computer are performed in this order: ______.", options: ["fetch, execute, and decode", "decode, execute, and fetch", "fetch, decode, and execute", "decode, fetch, and execute"], answer: 2 },
    { question: "The____controller features a parallel interface and daisy-chained connection for I/O devices.", options: ["SCSI", "FireWire", "USB", "IDE"], answer: 0 },
    { question: "Which optical storage device has the highest capacity?", options: ["CD-RAM", "CD-R", "CD-RW", "DVD"], answer: 3 },
    { question: "The earliest operating system, called (  ) operating systems, only had to ensure that resources were transferred from one job to the next.", options: ["batch", "time-sharing", "personal", "parallel"], answer: 0 },
    { question: "DOS is considered a (  ) operating system.", options: ["batch", "time-sharing", "parallel", "personal"], answer: 3 },
    { question: "The foundation of software engineering is ( ).", options: ["Process", "Tool", "Design", "Method"], answer: 0 },
    { question: "Which of the following is not the cause of the software crisis ( ).", options: ["Subjective neglect of demand analysis", "Over-emphasis is placed on software maintenance", "The wrong view of software development as programming", "The software itself is a logical part, and it is getting bigger and bigger"], answer: 1 },
    { question: "The following software belongs to the application software is ( ).", options: ["Financial management software", "Database", "Compiler", "Browser"], answer: 3 },
    { question: "Which of the following is a non-volatile memory?", options: ["RAM", "Cache", "ROM", "Register"], answer: 2 },
    { question: "In the OSI model, which layer is responsible for establishing, maintaining, and terminating connections?", options: ["Transport", "Network", "Session", "Presentation"], answer: 2 },
    { question: "Which of the following is an example of a high-level programming language?", options: ["Assembly", "C", "Machine code", "Binary"], answer: 1 },
    { question: "What does SQL stand for?", options: ["Structured Query Language", "Sequential Query Language", "Simple Query Language", "Standard Query Language"], answer: 0 },
    { question: "The primary function of the CPU's ALU is to perform (    ) operations.", options: ["arithmetic and logic", "data storage", "input and output", "network communication"], answer: 0 },
    { question: "Which protocol is used to translate domain names into IP addresses?", options: ["DNS", "HTTP", "FTP", "SMTP"], answer: 0 },
    { question: "The process of converting source code into machine code is known as (    ).", options: ["compilation", "linking", "executing", "interpreting"], answer: 0 },
    { question: "Which of the following is not a type of malware?", options: ["Virus", "Trojan", "Firewall", "Worm"], answer: 2 },
    { question: "The primary purpose of an operating system is to (    ).", options: ["provide a user interface", "manage hardware resources", "run applications", "connect to the internet"], answer: 1 },
    { question: "Which data structure uses LIFO (Last In First Out) principle?", options: ["Queue", "Stack", "Array", "List"], answer: 1 },
    { question: "The method of encryption where each letter of a message is shifted by a fixed number is called (    ).", options: ["Caesar Cipher", "RSA", "AES", "DES"], answer: 0 },
    { question: "In object-oriented programming, a class is best described as a (    ).", options: ["blueprint for objects", "single instance of an object", "method of an object", "type of variable"], answer: 0 },
    { question: "Which of the following is used for version control of source code?", options: ["Git", "SQL", "Java", "HTML"], answer: 0 },
    { question: "In binary notation, the number 1 is represented as (    ).", options: ["0", "1", "10", "11"], answer: 1 },
    { question: "Which software development model emphasizes iterative development with incremental improvements?", options: ["Waterfall", "Agile", "Spiral", "V-Model"], answer: 1 },
    { question: "The 'ping' command is used to (    ).", options: ["test network connectivity", "check disk space", "manage files", "edit text"], answer: 0 },
    { question: "Which component of a computer system is responsible for performing calculations and executing instructions?", options: ["Hard Drive", "Motherboard", "CPU", "RAM"], answer: 2 },
    { question: "In a relational database, a table that stores data about entities and their attributes is known as a (    ).", options: ["Schema", "View", "Relation", "Index"], answer: 2 },
    { question: "The process of debugging aims to (    ).", options: ["find and fix errors", "compile code", "optimize performance", "document software"], answer: 0 },
    { question: "Which sorting algorithm has the worst-case time complexity of O(n^2)?", options: ["Merge Sort", "Quick Sort", "Bubble Sort", "Heap Sort"], answer: 2 },
    { question: "Which of the following is a function of an operating system?", options: ["File management", "Network management", "Memory management", "All of the above"], answer: 3 },
    { question: "What does HTTP stand for?", options: ["Hypertext Transfer Protocol", "Hypertext Translation Protocol", "High Text Transfer Protocol", "Hyper Transfer Text Protocol"], answer: 0 },
    { question: "Which of the following is a type of loop structure in programming?", options: ["For loop", "If statement", "Switch statement", "Try-catch block"], answer: 0 },
    { question: "In programming, what is a 'bug'?", options: ["A type of error", "A debugging tool", "A function", "A variable"], answer: 0 },
    { question: "Which data structure is best suited for implementing a priority queue?", options: ["Heap", "Stack", "Queue", "Array"], answer: 0 },
    { question: "Which of the following is an example of a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], answer: 2 },
    { question: "In which layer of the OSI model does packet switching occur?", options: ["Network layer", "Data Link layer", "Physical layer", "Transport layer"], answer: 0 },
    { question: "What is the purpose of a compiler?", options: ["Translate high-level code into machine code", "Execute machine code", "Debug code", "Optimize code"], answer: 0 },
    { question: "Which of the following is not a programming paradigm?", options: ["Procedural", "Functional", "Object-Oriented", "Relational"], answer: 3 },
    { question: "What does API stand for?", options: ["Application Programming Interface", "Application Program Interface", "Advanced Programming Interface", "Advanced Program Interface"], answer: 0 },
    { question: "What is the primary use of an 'index' in a database?", options: ["Improve search performance", "Store large data", "Perform calculations", "Backup data"], answer: 0 },
    { question: "Which sorting algorithm is known for its 'divide and conquer' approach?", options: ["Merge Sort", "Selection Sort", "Bubble Sort", "Insertion Sort"], answer: 0 },
    { question: "What is the purpose of a 'kernel' in an operating system?", options: ["Manage hardware resources", "Provide a user interface", "Run applications", "Connect to the internet"], answer: 0 },
    { question: "Which type of memory is volatile?", options: ["RAM", "ROM", "Hard Drive", "Flash Memory"], answer: 0 },
    { question: "What does DNS stand for?", options: ["Domain Name System", "Dynamic Network Service", "Data Network System", "Domain Network Service"], answer: 0 },
    { question: "In object-oriented programming, what is 'inheritance'?", options: ["A way to create a new class from an existing class", "A method to hide data", "A way to manage memory", "A technique to handle errors"], answer: 0 },
    { question: "Which language is primarily used for web front-end development?", options: ["JavaScript", "Python", "Java", "C++"], answer: 0 },
    { question: "What is the purpose of 'virtual memory' in an operating system?", options: ["Extend the physical memory", "Increase processor speed", "Manage disk space", "Handle network requests"], answer: 0 },
    { question: "What does SQL stand for?", options: ["Structured Query Language", "Standard Query Language", "Sequential Query Language", "Simple Query Language"], answer: 0 },
    { question: "Which of the following is a type of 'software engineering' methodology?", options: ["Agile", "Hardware", "Networking", "Database"], answer: 0 },
    { question: "What is a 'race condition'?", options: ["An issue where the outcome depends on the sequence of events", "A type of software bug", "A system security vulnerability", "A memory leak"], answer: 0 },
    { question: "Which sorting algorithm is generally the most efficient for large datasets?", options: ["Merge Sort", "Bubble Sort", "Insertion Sort", "Selection Sort"], answer: 0 },
    { question: "In programming, what is 'refactoring'?", options: ["Improving the structure of code without changing its behavior", "Adding new features", "Fixing bugs", "Optimizing performance"], answer: 0 },
    { question: "What does IDE stand for?", options: ["Integrated Development Environment", "Internal Development Environment", "Internet Development Environment", "Interactive Development Environment"], answer: 0 },
    { question: "What is a 'data structure'?", options: ["A way to organize and store data", "A method for debugging code", "A type of programming language", "A database management system"], answer: 0 },
    { question: "Which of the following is a common use of the 'hash table' data structure?", options: ["Storing key-value pairs", "Implementing a stack", "Managing a queue", "Performing mathematical calculations"], answer: 0 },
    { question: "What does 'CRUD' stand for in database operations?", options: ["Create, Read, Update, Delete", "Compile, Run, Update, Debug", "Connect, Retrieve, Update, Delete", "Create, Read, Undo, Debug"], answer: 0 },
    { question: "Which of the following is a characteristic of 'object-oriented programming'?", options: ["Encapsulation", "Linear execution", "Functional abstraction", "Sequential processing"], answer: 0 },
    { question: "What is 'dynamic typing' in programming languages?", options: ["Type checking is done at runtime", "Type checking is done at compile-time", "Types are fixed and cannot change", "Data types are not used"], answer: 0 },
    { question: "In a relational database, what is a 'foreign key'?", options: ["A field that links to the primary key of another table", "A unique identifier for a record", "A data type for storing large text", "An index for optimizing search"], answer: 0 },
    { question: "Which algorithm is commonly used for encryption and decryption?", options: ["RSA", "Merge Sort", "Quick Sort", "Breadth-First Search"], answer: 0 },
    { question: "In which layer of the OSI model does routing occur?", options: ["Network layer", "Data Link layer", "Application layer", "Transport layer"], answer: 0 },
    { question: "What is 'abstraction' in object-oriented programming?", options: ["Hiding the complex implementation details", "Creating new objects from existing ones", "Managing memory efficiently", "Handling errors gracefully"], answer: 0 },
    { question: "Which of the following is a non-relational database?", options: ["MongoDB", "MySQL", "PostgreSQL", "Oracle"], answer: 0 },
    { question: "What does 'synchronization' mean in concurrent programming?", options: ["Ensuring that only one process accesses a resource at a time", "Speeding up the execution of code", "Balancing load across multiple servers", "Compiling code efficiently"], answer: 0 },
    { question: "Which of the following is an example of a high-level programming language?", options: ["Python", "Assembly", "Machine Code", "Binary"], answer: 0 },
    { question: "What is a 'linked list'?", options: ["A data structure with nodes containing data and references to the next node", "A type of database table", "A method of sorting data", "A form of file compression"], answer: 0 },
    { question: "Which protocol is used to send email messages over the internet?", options: ["SMTP", "FTP", "HTTP", "DNS"], answer: 0 },
    { question: "What does 'TCP' stand for in networking?", options: ["Transmission Control Protocol", "Transmission Code Protocol", "Text Communication Protocol", "Transport Control Protocol"], answer: 0 },
    { question: "What is the main purpose of 'unit testing'?", options: ["Test individual components for correctness", "Test the entire system", "Test the integration of multiple systems", "Test the performance of the system"], answer: 0 },
    { question: "Which of the following is a 'graph traversal' algorithm?", options: ["Depth-First Search", "Bubble Sort", "Binary Search", "Merge Sort"], answer: 0 },
    { question: "What does 'JSON' stand for?", options: ["JavaScript Object Notation", "Java Serialized Object Notation", "Java Standard Object Notation", "JavaScript Standard Object Notation"], answer: 0 },
    { question: "What is 'polymorphism' in object-oriented programming?", options: ["The ability of different classes to be treated as instances of the same class through a common interface", "The process of combining multiple objects", "The practice of reusing code", "The method of encapsulating data"], answer: 0 },
    { question: "Which of the following is a feature of 'dynamic programming'?", options: ["Breaking down a problem into simpler subproblems", "Sorting data efficiently", "Optimizing memory usage", "Handling concurrency issues"], answer: 0 },
];

function getRandomQuestions(num) {
    const shuffled = questions.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, num);
}

export default getRandomQuestions;
